# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddb13a721332a260eeb08a010a3bd5d14e5ac750409f09108b6e709b7e2cb51f69dc22ed8d419631ca2327be8fe469276e0edccf9b98afe8ffec0f4e54f3e19f

test:
  secret_key_base: ec2a0ca6f85098d2ef01d4fc2efffb10638193e83df42debf3d786d02251ee2d8a30fae0de5924df326c506a9dc5c7ea35b8a990700ef21bc7704cfd04c88187

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
